<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login col-sm-6 col-xs-12">
    <div class="block-title">
    <h3 class="title" id="block-customer-login-heading" role="heading" aria-level="2"><span><?php /* @escapeNotVerified */ echo __('Registered Customers') ?></span></h3>
    </div>
    <?php echo $block->getChildHtml('social-login-popup-authentication-social-login') ?>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
    <form class="form form-login" action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>" method="post" id="login-form" data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey'); ?>
            <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                <div class="field note margin-bottom10"><?php /* @escapeNotVerified */ echo __('If you have an account, sign in with your email address.') ?></div>
                <div class="field email required">
                    <div class="form-group">
                        <div class="control">
                            <input name="login[username]" placeholder="Email or Phone" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off" <?php endif; ?> id="email" type="text" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email or Phone') ?>" data-validate="{required:true, 'validate-phone-number-custom':true}">
                        </div>
                    </div>
                </div>
                <div class="field password required">
                    <div class="form-group">
                        <div class="control">
                            <input name="login[password]" placeholder="Password" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off" <?php endif; ?> class="input-text" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true}">
                        </div>
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
                <?php echo $block->getChildHtml('form.additional.info'); ?>
                <div class="actions-toolbar padding-top10">
                    <button type="submit" class="action login btn btn-primary btn-lg" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></button>
                    <a class="margin-left15 action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a>
                </div>
            </fieldset>
        </form>
    </div>
</div>

<style>
    .account-social-login .actions-toolbar.social-btn {
        margin-left: 0px !important;
    }

    .facebook-login .btn-facebook {
        margin-top: 10px !important;
        text-align: center;
        margin-right: 0px;
    }

    .google-login .btn-google {
        text-align: center;
        margin-top: 10px !important;
    }

    a.btn.btn-block.btn-social.btn-google {
        margin-right: 0;
    }

    .block.social-login-authentication-channel.account-social-login .block-content {
        display: flex;
        flex-direction: row;
        padding-bottom: 25px;
    }
    .account-social-login .actions-toolbar.social-btn-actions-toolbar .btn-facebook {
        width: 122% !important;
    }

    .account-social-login .actions-toolbar.social-btn-actions-toolbar .btn-google {
        width: 124% !important;
    }
    @media (max-width: 1199px) {
        .block.social-login-authentication-channel.account-social-login .block-content {
            display: flex;
            flex-direction: column;
            padding-bottom: 25px;

        }

        .account-social-login .actions-toolbar.social-btn-actions-toolbar .btn-facebook {
            width: 250% !important;
        }

        .account-social-login .actions-toolbar.social-btn-actions-toolbar .btn-google {
            width: 250% !important;
        }
    }
    @media (max-width: 767px) {
        .account-social-login .actions-toolbar.social-btn-actions-toolbar .btn-facebook {
            width: 100% !important;
        }

        .account-social-login .actions-toolbar.social-btn-actions-toolbar .btn-google {
            width: 100% !important;
        }
    }
</style>